### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by gurubee** [gurubee/note#46]
## Kubernetes 란 ?

- **Kunbernetes (k8s) : 컨테이너 오케스트레이션 플랫폼**
  - 공식 홈페이지 : https://kubernetes.io/
  - Github : https://github.com/kubernetes/kubernetes
- 오케스트레이션 (Orchestration)
  - 복잡한 단계를 관리하고 요소들의 유기적인 관계를 미리 정의해 손쉽게 사용하도록 서비스를 제공하는것
- 컨테이너 오케스트레이션
  - 다수의 컨테이너를 유기적으로 연결, 실행, 종료할 뿐만 아니라 상태를 추적하고 보존하는 등 컨테이너를 안정적으로 사용할 수 있게 만들어 주는 것
  - 다수의 서버위에서 컨테이너의 전반적인 라이프사이클을 관리해주는 플랫폼

<br>

### 쿠버네티스란 무엇인가 ?
- 구글의 “컨테이너 플랫폼 or 마이크로서비스 플랫폼 or 이식성 있는 클라우드 플랫폼”
- Stateless, Stateful, 데이터 처리등 다양한 어플리케이션 타입을 컨테이너로 구동할 수 있게 해줌
- 현재는 리눅스 재단 산하 CNCF (Cloud Native Computing Foundation) 에서 관리
- 현재 컨테이너 오케스트레이션 시스템의 de facto 이며 GCP, AWS, Azure 등의 클라우드 서비스에서 Kubernetes 서비스를 제공

<br>

![components-of-kubernetes](https://github.com/gurubee/note/assets/18006053/51662a85-0e38-4c57-a373-2280bb3065a3)

<br><br>

## Kubernetes Objects
- Kubernetes 는 선언적 (Declarative) 으로 동작하는 시스템 ([link](https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/))
- Kubernetes Object 를 Kubernetes 시스템에 반영하는 방식으로 동작

### Kubernetes Object Config (yaml or json)

```
# Kubernetes Object Config
$ cat Pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-application-name
spec:
  containers:
  - name: java
    image: my-spring-boot-sample-image:0.1
```

<br>

### kubectl
- Kubernetes 의 Command Line Interface

```
kubectl create -f Pod.yaml
kubectl apply -f Pod.yaml
kubectl delete -f Pod.yaml
kubectl get pods xxxxx
kubectl describe pods xxxxx
```

- Kubernetes Object 는 Kubernetes 시스템의 상태를 표현하는 구성 단위이며 Basic 과 Controller 타입이 있다.
- 기본 오브젝트(Basic Object)
  - 쿠버네티스에 의해서 배포 및 관리되는 가장 기본적인 오브젝트로, Pod, Service, Volume, Namespace 4가지가 있다.
- Controller
  - 기본 오브젝트를 생성하고 관리하는 역할을 하는 오브젝트.
  - Deployment, Replication Controller, ReplicationSet, DeamonSet, Job, StatefulSet 등이 있다.

<br><br>

## Pod
- 쿠버네티스의 최소 실행 단위 → 쿠버네티스에서 배포할 수 있는 가장 작은 단위
- Kubernetes 에서는  여러개의 컨테이너를 Pod으로 그룹화 배포한다.
- 한 Pod 내의 컨테이너는 네트워크와 로컬 디스크 볼륨 (컨테이너 스토리지가 아님) 을 공유한다.

<br>

### Pod 의 특징

> 쿠버네티스에서의 파드는 무언가가 구동 중인 상태를 유지하기 위해 동원되는 일회성 자원이며, 필요에 따라 언제든 삭제될 수 있는 것임을 유념해야 한다.

- 1개이상의 컨테이너 실행 가능하다. → 상황에 따라서는 2개, 많게는 3개까지 컨테이너를 실행한다.
- 동일 노드에 할당 → Pod 내에서 실행되는 컨테이너들은 반드시 동일한 노드에 할당되며 Pod 삭제시, Pod내의 모든 컨테이너가 종료된다.
- Pod 리소스는 노드 IP와 별개로 클러스터 내에서 접근 가능한 고유의 ip를 할당 받는다. 따라서, 쿠버네티스에서는 다른 노드에 위치한 POD간이라 하더라도, nat 통신 없이 고유 IP로 접근 가능
- IP 공유 → Pod내에 컨테이너들은 서로 ip를 공유한다. (localhost를 통해 접근 가능하며 port를 이용하여 구분)
- Volume 공유 → Pod 안의 컨테이너들은 동일한 볼륨과 연결 가능
- 파드는 기본적으로 반영속적(ephemeral)이다.

![pod-overview](https://github.com/gurubee/note/assets/18006053/719efa84-533c-4ff9-bf64-9ed11f937e03)

<br>

### Pod Manifest

- 쿠버네티스는 모든 리소스는 YAML 형태의 선언형 명령 정의서로 표현할수 있다.

```
$ cat Pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app.kubernetes.io/instance: example
spec:
  containers:
  - name: ngnix
    image: ngnix
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /share
      name: my-emptydir
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /share
      name: my-emptydir
  volumes:
  - name: my-emptydir
    emptyDir: {}
```

<br><br>

- 어플리케이션 패키징 : 컨테이너
- 컨테이너의 복제 집합 생성 :  ReplicaSet
- 서비스에 대한 트래픽 로드밸런싱 : 인그레스 컨트롤러
- 어플리케이션 배포 관리 : Deployment

<br><br>

## ReplicaSet
- 여러개의 Pod 을 관리해주는 역할을 수행
- ReplicaSet 을 생성하면 지정된 숫자 (Replicas) 에 맞춰 Pod 을 생성하고 관리
- ReplicaSet Object 를 생성하면 Kubernetes 의 Replication Controller 에 의해 설정에 맞는 Pod 을 관리
  - replicas: Pod 의 개수
  - selector: 이 ReplicaSet 에 속하는 Pod 을 선택할 Pod 의 Label
  - template: Pod 의 스펙을 정의

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example
  labels:
    app.kubernetes.io/instance: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: example
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: example
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

<br><br>

## Deployment
- Pod을 구동할 때 Deployment Object를 생성하면 된다.
- 여러개의 ReplicaSet 을 관리하고 Rolling Update 가 가능하게 함.
- Deployment 를 생성하면 설정에 따라 ReplicaSet 을 생성하고 관리

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app.kubernetes.io/instance: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: example
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: example
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

- Deployment 의 .spec 을 수정하면 Kubernetes 의 DeploymentController 는 이 변경에 맞춰서 현재 상태를 적용합니다

<img width="652" alt="deployments" src="https://github.com/gurubee/note/assets/18006053/3316e6f8-87b0-4833-bbc4-227462f343f5">

<br><br>

## Service
- Deployment 나 ReplicaSet 에 의해 관리되는 여러 Pod(s) 들의 접근 Endpoint 를 제공

```
kind: Service
apiVersion: v1
metadata:
  name: example
spec:
  selector:
    app.kubernetes.io/instance: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
```

- Pod에 할당되는 IP는 랜덤하게 진행되고, 쿠버네티스에 의해 자동으로 종료되고, 재시작되기도 하므로, 고정된 엔드포인트로 이용이 어렵다.
- 서비스 object를 정의하면 고정된 IP와 포트로 외부에서 접근할 수 있도록 한다.
- 여러 pod을 Label을 기반으로 묶어서 서비스에 참여시키며, 이 Pod들 간에 로드밸런싱기능(L4 switch)을 기본으로 제공해준다.
- 생성된 서비스는 고유한 DNS이름을 가질 수 있다.
- 서비스의 타입을 설정하여 외부에서의 접근 가능성 여부를 설정할 수 있음.
  - ClusterIP : 내부에서만 접근 가능한 IP를 서비스에 할당함.
  - LoadBalancer : 외부에서 접근이 가능한 External IP를 할당함.
- 기본적으로 지원되는 L4 switch기능외에, 서비스에 Ingress를 정의하고 그 구현체를 추가하는 방식으로 L7 swiching 기능을 사용할 수 있음.
- [kubernetes 메뉴얼](https://kubernetes.io/docs/concepts/services-networking/service/)

### 가능한 서비스 방식
![service_type](https://github.com/gurubee/note/assets/18006053/cbbc4c6c-7f30-4e7c-8f85-b176c6e9ca97)

<br><br>

## Statefulset
- “Stateful’ 한 어플리케이션을 관리하기 위한 오브젝트 입니다.
- Deployment 와 마찬가지로 Pod(s) 를 관리하지만 각각의 Pod 이 고유한   Identity 를 가질 수 있습니다.
  - Identity: DNS 주소, Local/Remote 볼륨, Scale in/out 순서, Update 순서
- MongoDB 예제
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/instance: nginx-statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app.kubernetes.io/instance: nginx-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-statefulset
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.7.6
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

![statefulset](https://github.com/gurubee/note/assets/18006053/25aba31a-322b-48ee-a144-11d618becb5e)

<br><br>

## ConfigMap
- Pod 에 환경변수나 설정 파일을 전달할때 사용하는 오브젝트로 KEY:VALUE 형태로 정의 합니다
- [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
- Configuration Example
```
cat myconfig.conf
project=ncc
cluster=ad1
namespace=edu
```

- Create ConfigMap
`kubectl create configmap example-config --from-file=./myconfig.conf`

- 환경 변수로 사용할때
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: example
      image: nginx:1.7.6
      env:
        - name: WHAT_IS_MY_PROJECT
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: project
```

- 설정 파일로 사용할 때
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: example
      image: nginx:1.7.6
      volumeMounts:
      - name: example-volume
      mountPath: /config
  volumes:
    - name: example-volume
      configMap:
        name: example-config
```
